webtalk_init -webtalk_dir C:/Users/Dell/Downloads/Log_Mulitplier/Log Multiplier Gate Level/Log Multiplier Gate Level.sim/sim_1/behav/xsim/xsim.dir/Priority_Encoder_V_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 23 15:14:43 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "68025648-3bdc-4f47-9850-c8dce8f8dc87" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "be0b3dc9d63b4d98a04bdac7e675513e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "90 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7156_KB" -context "xsim\\usage"
webtalk_transmit -clientid 700620885 -regid "" -xml C:/Users/Dell/Downloads/Log_Mulitplier/Log Multiplier Gate Level/Log Multiplier Gate Level.sim/sim_1/behav/xsim/xsim.dir/Priority_Encoder_V_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Dell/Downloads/Log_Mulitplier/Log Multiplier Gate Level/Log Multiplier Gate Level.sim/sim_1/behav/xsim/xsim.dir/Priority_Encoder_V_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Dell/Downloads/Log_Mulitplier/Log Multiplier Gate Level/Log Multiplier Gate Level.sim/sim_1/behav/xsim/xsim.dir/Priority_Encoder_V_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
